/********************************************************************************
** Form generated from reading UI file 'fight_fight.ui'
**
** Created by: Qt User Interface Compiler version 5.4.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FIGHT_FIGHT_H
#define UI_FIGHT_FIGHT_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_fight_fight
{
public:
    QTextEdit *edit_display;
    QPushButton *btn_quit;
    QPushButton *btn_start;
    QCheckBox *checkBox_auto;
    QCheckBox *checkBox_hp;
    QCheckBox *checkBox_mp;
    QCheckBox *checkBox_ap;
    QComboBox *comboBox_hp;
    QComboBox *comboBox_mp;
    QComboBox *comboBox_ap;
    QCheckBox *checkBox_concise;
    QCheckBox *checkBox_quick;
    QLabel *label_role_head;
    QLabel *label_monster_head;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *edit_hp;
    QLineEdit *edit_mp;
    QLineEdit *edit_ap;
    QLineEdit *edit_role_name;
    QLineEdit *edit_role_level;
    QLineEdit *edit_role_PhysicsAttack;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLineEdit *edit_role_MagicAttack;
    QLineEdit *edit_role_SpellAttack;
    QLineEdit *edit_role_PhysicsGuard;
    QLineEdit *edit_role_ElementGuard;
    QLineEdit *edit_role_rhp;
    QLineEdit *edit_role_rmp;
    QLineEdit *edit_role_rap;
    QLineEdit *edit_role_extrarate;
    QLineEdit *edit_role_extrahurt;
    QLineEdit *edit_role_AttackSpeed;
    QLineEdit *edit_role_penetrate;
    QLineEdit *edit_monster_penetrate;
    QLabel *label_18;
    QLabel *label_19;
    QLineEdit *edit_monster_ElementGuard;
    QLineEdit *edit_monster_rhp;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLineEdit *edit_monster_rmp;
    QLabel *label_23;
    QLineEdit *edit_monster_extrarate;
    QLineEdit *edit_monster_AttackSpeed;
    QLineEdit *edit_monster_PhysicsAttack;
    QLineEdit *edit_monster_PhysicsGuard;
    QLabel *label_24;
    QLineEdit *edit_monster_rap;
    QLineEdit *edit_monster_MagicAttack;
    QLabel *label_25;
    QLabel *label_26;
    QLineEdit *edit_monster_extrahurt;
    QLabel *label_27;
    QLabel *label_28;
    QLineEdit *edit_monster_SpellAttack;
    QLabel *label_29;
    QLineEdit *edit_monster_name;
    QLabel *label_30;
    QLabel *label_31;
    QLineEdit *edit_monster_level;
    QLabel *label_32;
    QProgressBar *progressBar_role_hp;
    QProgressBar *progressBar_role_mp;
    QProgressBar *progressBar_role_ap;
    QProgressBar *progressBar_monster_ap;
    QProgressBar *progressBar_monster_hp;
    QProgressBar *progressBar_monster_mp;
    QGroupBox *groupBox;
    QCheckBox *checkBox_MultipleReputation;
    QCheckBox *checkBox_MultipleDrop;
    QCheckBox *checkBox_MultipleExp;
    QLineEdit *edit_MultipleExp;
    QLineEdit *edit_MultipleDrop;
    QLineEdit *edit_MultipleReputation;
    QProgressBar *progressBar_role_exp;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;

    void setupUi(QWidget *fight_fight)
    {
        if (fight_fight->objectName().isEmpty())
            fight_fight->setObjectName(QStringLiteral("fight_fight"));
        fight_fight->resize(880, 625);
        fight_fight->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        edit_display = new QTextEdit(fight_fight);
        edit_display->setObjectName(QStringLiteral("edit_display"));
        edit_display->setGeometry(QRect(250, 168, 381, 321));
        btn_quit = new QPushButton(fight_fight);
        btn_quit->setObjectName(QStringLiteral("btn_quit"));
        btn_quit->setGeometry(QRect(500, 128, 75, 23));
        btn_start = new QPushButton(fight_fight);
        btn_start->setObjectName(QStringLiteral("btn_start"));
        btn_start->setGeometry(QRect(340, 128, 75, 23));
        checkBox_auto = new QCheckBox(fight_fight);
        checkBox_auto->setObjectName(QStringLiteral("checkBox_auto"));
        checkBox_auto->setGeometry(QRect(560, 20, 71, 22));
        checkBox_hp = new QCheckBox(fight_fight);
        checkBox_hp->setObjectName(QStringLiteral("checkBox_hp"));
        checkBox_hp->setGeometry(QRect(250, 20, 51, 22));
        checkBox_hp->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        checkBox_mp = new QCheckBox(fight_fight);
        checkBox_mp->setObjectName(QStringLiteral("checkBox_mp"));
        checkBox_mp->setGeometry(QRect(250, 48, 51, 22));
        checkBox_mp->setStyleSheet(QStringLiteral("color: rgb(0, 0, 127);"));
        checkBox_ap = new QCheckBox(fight_fight);
        checkBox_ap->setObjectName(QStringLiteral("checkBox_ap"));
        checkBox_ap->setEnabled(false);
        checkBox_ap->setGeometry(QRect(250, 80, 51, 22));
        checkBox_ap->setStyleSheet(QStringLiteral("color: rgb(143, 143, 0);"));
        comboBox_hp = new QComboBox(fight_fight);
        comboBox_hp->setObjectName(QStringLiteral("comboBox_hp"));
        comboBox_hp->setGeometry(QRect(350, 20, 201, 22));
        comboBox_mp = new QComboBox(fight_fight);
        comboBox_mp->setObjectName(QStringLiteral("comboBox_mp"));
        comboBox_mp->setGeometry(QRect(350, 48, 201, 22));
        comboBox_ap = new QComboBox(fight_fight);
        comboBox_ap->setObjectName(QStringLiteral("comboBox_ap"));
        comboBox_ap->setEnabled(false);
        comboBox_ap->setGeometry(QRect(350, 80, 201, 22));
        checkBox_concise = new QCheckBox(fight_fight);
        checkBox_concise->setObjectName(QStringLiteral("checkBox_concise"));
        checkBox_concise->setGeometry(QRect(560, 48, 71, 22));
        checkBox_quick = new QCheckBox(fight_fight);
        checkBox_quick->setObjectName(QStringLiteral("checkBox_quick"));
        checkBox_quick->setEnabled(false);
        checkBox_quick->setGeometry(QRect(560, 80, 71, 22));
        label_role_head = new QLabel(fight_fight);
        label_role_head->setObjectName(QStringLiteral("label_role_head"));
        label_role_head->setGeometry(QRect(50, 20, 150, 150));
        label_role_head->setPixmap(QPixmap(QString::fromUtf8(":/head/Resources/head/role_z_m_h.png")));
        label_monster_head = new QLabel(fight_fight);
        label_monster_head->setObjectName(QStringLiteral("label_monster_head"));
        label_monster_head->setGeometry(QRect(680, 20, 150, 150));
        label_monster_head->setPixmap(QPixmap(QString::fromUtf8(":/head/Resources/head/role_z_m_h.png")));
        label_3 = new QLabel(fight_fight);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(50, 184, 24, 16));
        label_3->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        label_4 = new QLabel(fight_fight);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(50, 208, 24, 16));
        label_4->setStyleSheet(QStringLiteral("color: rgb(0, 0, 127);"));
        label_5 = new QLabel(fight_fight);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(50, 232, 24, 16));
        label_5->setStyleSheet(QStringLiteral("color: rgb(143, 143, 0);"));
        edit_hp = new QLineEdit(fight_fight);
        edit_hp->setObjectName(QStringLiteral("edit_hp"));
        edit_hp->setGeometry(QRect(300, 20, 25, 22));
        edit_hp->setMaxLength(2);
        edit_mp = new QLineEdit(fight_fight);
        edit_mp->setObjectName(QStringLiteral("edit_mp"));
        edit_mp->setGeometry(QRect(300, 48, 25, 22));
        edit_ap = new QLineEdit(fight_fight);
        edit_ap->setObjectName(QStringLiteral("edit_ap"));
        edit_ap->setEnabled(false);
        edit_ap->setGeometry(QRect(300, 80, 25, 22));
        edit_role_name = new QLineEdit(fight_fight);
        edit_role_name->setObjectName(QStringLiteral("edit_role_name"));
        edit_role_name->setGeometry(QRect(50, 280, 91, 20));
        edit_role_name->setReadOnly(true);
        edit_role_level = new QLineEdit(fight_fight);
        edit_role_level->setObjectName(QStringLiteral("edit_role_level"));
        edit_role_level->setGeometry(QRect(150, 280, 60, 20));
        edit_role_level->setReadOnly(true);
        edit_role_PhysicsAttack = new QLineEdit(fight_fight);
        edit_role_PhysicsAttack->setObjectName(QStringLiteral("edit_role_PhysicsAttack"));
        edit_role_PhysicsAttack->setGeometry(QRect(100, 312, 100, 20));
        edit_role_PhysicsAttack->setReadOnly(true);
        label_6 = new QLabel(fight_fight);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(60, 312, 24, 20));
        label_7 = new QLabel(fight_fight);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(60, 336, 24, 20));
        label_8 = new QLabel(fight_fight);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(60, 360, 24, 20));
        label_9 = new QLabel(fight_fight);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(60, 432, 24, 20));
        label_10 = new QLabel(fight_fight);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(60, 408, 24, 20));
        label_11 = new QLabel(fight_fight);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(60, 384, 24, 20));
        label_12 = new QLabel(fight_fight);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(60, 528, 48, 20));
        label_13 = new QLabel(fight_fight);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(60, 480, 24, 20));
        label_14 = new QLabel(fight_fight);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(60, 456, 24, 20));
        label_15 = new QLabel(fight_fight);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(60, 504, 48, 20));
        label_16 = new QLabel(fight_fight);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(60, 576, 48, 20));
        label_17 = new QLabel(fight_fight);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(60, 552, 48, 20));
        edit_role_MagicAttack = new QLineEdit(fight_fight);
        edit_role_MagicAttack->setObjectName(QStringLiteral("edit_role_MagicAttack"));
        edit_role_MagicAttack->setGeometry(QRect(100, 336, 100, 20));
        edit_role_MagicAttack->setReadOnly(true);
        edit_role_SpellAttack = new QLineEdit(fight_fight);
        edit_role_SpellAttack->setObjectName(QStringLiteral("edit_role_SpellAttack"));
        edit_role_SpellAttack->setGeometry(QRect(100, 360, 100, 20));
        edit_role_SpellAttack->setReadOnly(true);
        edit_role_PhysicsGuard = new QLineEdit(fight_fight);
        edit_role_PhysicsGuard->setObjectName(QStringLiteral("edit_role_PhysicsGuard"));
        edit_role_PhysicsGuard->setGeometry(QRect(100, 384, 100, 20));
        edit_role_PhysicsGuard->setReadOnly(true);
        edit_role_ElementGuard = new QLineEdit(fight_fight);
        edit_role_ElementGuard->setObjectName(QStringLiteral("edit_role_ElementGuard"));
        edit_role_ElementGuard->setGeometry(QRect(100, 408, 100, 20));
        edit_role_ElementGuard->setReadOnly(true);
        edit_role_rhp = new QLineEdit(fight_fight);
        edit_role_rhp->setObjectName(QStringLiteral("edit_role_rhp"));
        edit_role_rhp->setGeometry(QRect(100, 432, 100, 20));
        edit_role_rhp->setReadOnly(true);
        edit_role_rmp = new QLineEdit(fight_fight);
        edit_role_rmp->setObjectName(QStringLiteral("edit_role_rmp"));
        edit_role_rmp->setGeometry(QRect(100, 456, 100, 20));
        edit_role_rmp->setReadOnly(true);
        edit_role_rap = new QLineEdit(fight_fight);
        edit_role_rap->setObjectName(QStringLiteral("edit_role_rap"));
        edit_role_rap->setGeometry(QRect(100, 480, 100, 20));
        edit_role_rap->setReadOnly(true);
        edit_role_extrarate = new QLineEdit(fight_fight);
        edit_role_extrarate->setObjectName(QStringLiteral("edit_role_extrarate"));
        edit_role_extrarate->setGeometry(QRect(120, 504, 80, 20));
        edit_role_extrarate->setReadOnly(true);
        edit_role_extrahurt = new QLineEdit(fight_fight);
        edit_role_extrahurt->setObjectName(QStringLiteral("edit_role_extrahurt"));
        edit_role_extrahurt->setGeometry(QRect(120, 528, 80, 20));
        edit_role_extrahurt->setReadOnly(true);
        edit_role_AttackSpeed = new QLineEdit(fight_fight);
        edit_role_AttackSpeed->setObjectName(QStringLiteral("edit_role_AttackSpeed"));
        edit_role_AttackSpeed->setGeometry(QRect(120, 552, 80, 20));
        edit_role_AttackSpeed->setReadOnly(true);
        edit_role_penetrate = new QLineEdit(fight_fight);
        edit_role_penetrate->setObjectName(QStringLiteral("edit_role_penetrate"));
        edit_role_penetrate->setGeometry(QRect(120, 576, 80, 20));
        edit_role_penetrate->setReadOnly(true);
        edit_monster_penetrate = new QLineEdit(fight_fight);
        edit_monster_penetrate->setObjectName(QStringLiteral("edit_monster_penetrate"));
        edit_monster_penetrate->setGeometry(QRect(740, 576, 80, 20));
        edit_monster_penetrate->setReadOnly(true);
        label_18 = new QLabel(fight_fight);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(680, 480, 24, 20));
        label_19 = new QLabel(fight_fight);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(680, 576, 48, 20));
        edit_monster_ElementGuard = new QLineEdit(fight_fight);
        edit_monster_ElementGuard->setObjectName(QStringLiteral("edit_monster_ElementGuard"));
        edit_monster_ElementGuard->setGeometry(QRect(720, 408, 100, 20));
        edit_monster_ElementGuard->setReadOnly(true);
        edit_monster_rhp = new QLineEdit(fight_fight);
        edit_monster_rhp->setObjectName(QStringLiteral("edit_monster_rhp"));
        edit_monster_rhp->setGeometry(QRect(720, 432, 100, 20));
        edit_monster_rhp->setReadOnly(true);
        label_20 = new QLabel(fight_fight);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(680, 312, 24, 20));
        label_21 = new QLabel(fight_fight);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(680, 408, 24, 20));
        label_22 = new QLabel(fight_fight);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(680, 360, 24, 20));
        edit_monster_rmp = new QLineEdit(fight_fight);
        edit_monster_rmp->setObjectName(QStringLiteral("edit_monster_rmp"));
        edit_monster_rmp->setGeometry(QRect(720, 456, 100, 20));
        edit_monster_rmp->setReadOnly(true);
        label_23 = new QLabel(fight_fight);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(680, 384, 24, 20));
        edit_monster_extrarate = new QLineEdit(fight_fight);
        edit_monster_extrarate->setObjectName(QStringLiteral("edit_monster_extrarate"));
        edit_monster_extrarate->setGeometry(QRect(740, 504, 80, 20));
        edit_monster_extrarate->setReadOnly(true);
        edit_monster_AttackSpeed = new QLineEdit(fight_fight);
        edit_monster_AttackSpeed->setObjectName(QStringLiteral("edit_monster_AttackSpeed"));
        edit_monster_AttackSpeed->setGeometry(QRect(740, 552, 80, 20));
        edit_monster_AttackSpeed->setReadOnly(true);
        edit_monster_PhysicsAttack = new QLineEdit(fight_fight);
        edit_monster_PhysicsAttack->setObjectName(QStringLiteral("edit_monster_PhysicsAttack"));
        edit_monster_PhysicsAttack->setGeometry(QRect(720, 312, 100, 20));
        edit_monster_PhysicsAttack->setReadOnly(true);
        edit_monster_PhysicsGuard = new QLineEdit(fight_fight);
        edit_monster_PhysicsGuard->setObjectName(QStringLiteral("edit_monster_PhysicsGuard"));
        edit_monster_PhysicsGuard->setGeometry(QRect(720, 384, 100, 20));
        edit_monster_PhysicsGuard->setReadOnly(true);
        label_24 = new QLabel(fight_fight);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(680, 528, 48, 20));
        edit_monster_rap = new QLineEdit(fight_fight);
        edit_monster_rap->setObjectName(QStringLiteral("edit_monster_rap"));
        edit_monster_rap->setGeometry(QRect(720, 480, 100, 20));
        edit_monster_rap->setReadOnly(true);
        edit_monster_MagicAttack = new QLineEdit(fight_fight);
        edit_monster_MagicAttack->setObjectName(QStringLiteral("edit_monster_MagicAttack"));
        edit_monster_MagicAttack->setGeometry(QRect(720, 336, 100, 20));
        edit_monster_MagicAttack->setReadOnly(true);
        label_25 = new QLabel(fight_fight);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(680, 456, 24, 20));
        label_26 = new QLabel(fight_fight);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(680, 336, 24, 20));
        edit_monster_extrahurt = new QLineEdit(fight_fight);
        edit_monster_extrahurt->setObjectName(QStringLiteral("edit_monster_extrahurt"));
        edit_monster_extrahurt->setGeometry(QRect(740, 528, 80, 20));
        edit_monster_extrahurt->setReadOnly(true);
        label_27 = new QLabel(fight_fight);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(680, 552, 48, 20));
        label_28 = new QLabel(fight_fight);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(680, 504, 48, 20));
        edit_monster_SpellAttack = new QLineEdit(fight_fight);
        edit_monster_SpellAttack->setObjectName(QStringLiteral("edit_monster_SpellAttack"));
        edit_monster_SpellAttack->setGeometry(QRect(720, 360, 100, 20));
        edit_monster_SpellAttack->setReadOnly(true);
        label_29 = new QLabel(fight_fight);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(680, 432, 24, 20));
        edit_monster_name = new QLineEdit(fight_fight);
        edit_monster_name->setObjectName(QStringLiteral("edit_monster_name"));
        edit_monster_name->setGeometry(QRect(740, 280, 91, 20));
        edit_monster_name->setReadOnly(true);
        label_30 = new QLabel(fight_fight);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(670, 232, 24, 16));
        label_30->setStyleSheet(QStringLiteral("color: rgb(143, 143, 0);"));
        label_31 = new QLabel(fight_fight);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(670, 208, 24, 16));
        label_31->setStyleSheet(QStringLiteral("color: rgb(0, 0, 127);"));
        edit_monster_level = new QLineEdit(fight_fight);
        edit_monster_level->setObjectName(QStringLiteral("edit_monster_level"));
        edit_monster_level->setGeometry(QRect(670, 280, 60, 20));
        edit_monster_level->setReadOnly(true);
        label_32 = new QLabel(fight_fight);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(670, 184, 24, 16));
        label_32->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        progressBar_role_hp = new QProgressBar(fight_fight);
        progressBar_role_hp->setObjectName(QStringLiteral("progressBar_role_hp"));
        progressBar_role_hp->setGeometry(QRect(80, 184, 131, 16));
        progressBar_role_hp->setValue(24);
        progressBar_role_hp->setAlignment(Qt::AlignCenter);
        progressBar_role_mp = new QProgressBar(fight_fight);
        progressBar_role_mp->setObjectName(QStringLiteral("progressBar_role_mp"));
        progressBar_role_mp->setGeometry(QRect(80, 208, 131, 16));
        progressBar_role_mp->setValue(24);
        progressBar_role_mp->setAlignment(Qt::AlignCenter);
        progressBar_role_ap = new QProgressBar(fight_fight);
        progressBar_role_ap->setObjectName(QStringLiteral("progressBar_role_ap"));
        progressBar_role_ap->setGeometry(QRect(80, 232, 131, 16));
        progressBar_role_ap->setMaximum(10);
        progressBar_role_ap->setValue(0);
        progressBar_role_ap->setAlignment(Qt::AlignCenter);
        progressBar_monster_ap = new QProgressBar(fight_fight);
        progressBar_monster_ap->setObjectName(QStringLiteral("progressBar_monster_ap"));
        progressBar_monster_ap->setGeometry(QRect(700, 232, 131, 16));
        progressBar_monster_ap->setMaximum(10);
        progressBar_monster_ap->setValue(0);
        progressBar_monster_ap->setAlignment(Qt::AlignCenter);
        progressBar_monster_hp = new QProgressBar(fight_fight);
        progressBar_monster_hp->setObjectName(QStringLiteral("progressBar_monster_hp"));
        progressBar_monster_hp->setGeometry(QRect(700, 184, 131, 16));
        progressBar_monster_hp->setValue(24);
        progressBar_monster_hp->setAlignment(Qt::AlignCenter);
        progressBar_monster_mp = new QProgressBar(fight_fight);
        progressBar_monster_mp->setObjectName(QStringLiteral("progressBar_monster_mp"));
        progressBar_monster_mp->setGeometry(QRect(700, 208, 131, 16));
        progressBar_monster_mp->setValue(24);
        progressBar_monster_mp->setAlignment(Qt::AlignCenter);
        groupBox = new QGroupBox(fight_fight);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(250, 503, 381, 89));
        checkBox_MultipleReputation = new QCheckBox(groupBox);
        checkBox_MultipleReputation->setObjectName(QStringLiteral("checkBox_MultipleReputation"));
        checkBox_MultipleReputation->setGeometry(QRect(120, 64, 95, 16));
        checkBox_MultipleDrop = new QCheckBox(groupBox);
        checkBox_MultipleDrop->setObjectName(QStringLiteral("checkBox_MultipleDrop"));
        checkBox_MultipleDrop->setGeometry(QRect(120, 40, 95, 16));
        checkBox_MultipleExp = new QCheckBox(groupBox);
        checkBox_MultipleExp->setObjectName(QStringLiteral("checkBox_MultipleExp"));
        checkBox_MultipleExp->setGeometry(QRect(120, 16, 95, 16));
        edit_MultipleExp = new QLineEdit(groupBox);
        edit_MultipleExp->setObjectName(QStringLiteral("edit_MultipleExp"));
        edit_MultipleExp->setGeometry(QRect(220, 16, 81, 20));
        edit_MultipleExp->setReadOnly(true);
        edit_MultipleDrop = new QLineEdit(groupBox);
        edit_MultipleDrop->setObjectName(QStringLiteral("edit_MultipleDrop"));
        edit_MultipleDrop->setGeometry(QRect(220, 40, 81, 20));
        edit_MultipleDrop->setReadOnly(true);
        edit_MultipleReputation = new QLineEdit(groupBox);
        edit_MultipleReputation->setObjectName(QStringLiteral("edit_MultipleReputation"));
        edit_MultipleReputation->setGeometry(QRect(220, 64, 81, 20));
        edit_MultipleReputation->setReadOnly(true);
        progressBar_role_exp = new QProgressBar(fight_fight);
        progressBar_role_exp->setObjectName(QStringLiteral("progressBar_role_exp"));
        progressBar_role_exp->setGeometry(QRect(0, 608, 880, 16));
        progressBar_role_exp->setValue(24);
        progressBar_role_exp->setTextVisible(false);
        label_33 = new QLabel(fight_fight);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(0, 0, 12, 12));
        label_34 = new QLabel(fight_fight);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(870, 0, 12, 12));
        label_35 = new QLabel(fight_fight);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(330, 20, 6, 22));
        label_35->setStyleSheet(QStringLiteral("color: rgb(255, 0, 0);"));
        label_36 = new QLabel(fight_fight);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(330, 50, 6, 22));
        label_36->setStyleSheet(QStringLiteral("color: rgb(0, 0, 127);"));
        label_37 = new QLabel(fight_fight);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(330, 80, 6, 22));
        label_37->setStyleSheet(QStringLiteral("color: rgb(143, 143, 0);"));

        retranslateUi(fight_fight);

        QMetaObject::connectSlotsByName(fight_fight);
    } // setupUi

    void retranslateUi(QWidget *fight_fight)
    {
        fight_fight->setWindowTitle(QApplication::translate("fight_fight", "fight_fight", 0));
        btn_quit->setText(QApplication::translate("fight_fight", "\351\200\200\345\207\272\346\210\230\346\226\227", 0));
        btn_start->setText(QApplication::translate("fight_fight", "\345\274\200\345\247\213\346\210\230\346\226\227", 0));
        checkBox_auto->setText(QApplication::translate("fight_fight", "\350\207\252\345\212\250\346\210\230\346\226\227", 0));
        checkBox_hp->setText(QApplication::translate("fight_fight", "\344\275\223\345\212\233", 0));
        checkBox_mp->setText(QApplication::translate("fight_fight", "\351\255\224\346\263\225", 0));
        checkBox_ap->setText(QApplication::translate("fight_fight", "\346\200\222\346\260\224", 0));
        checkBox_concise->setText(QApplication::translate("fight_fight", "\347\256\200\346\264\201\346\250\241\345\274\217", 0));
        checkBox_quick->setText(QApplication::translate("fight_fight", "\345\277\253\351\200\237\346\210\230\346\226\227", 0));
        label_role_head->setText(QString());
        label_monster_head->setText(QString());
        label_3->setText(QApplication::translate("fight_fight", "\344\275\223\345\212\233", 0));
        label_4->setText(QApplication::translate("fight_fight", "\351\255\224\346\263\225", 0));
        label_5->setText(QApplication::translate("fight_fight", "\346\200\222\346\260\224", 0));
        edit_hp->setInputMask(QApplication::translate("fight_fight", "99", 0));
        edit_hp->setText(QApplication::translate("fight_fight", "50", 0));
        edit_mp->setInputMask(QApplication::translate("fight_fight", "99", 0));
        edit_mp->setText(QApplication::translate("fight_fight", "50", 0));
        edit_ap->setInputMask(QApplication::translate("fight_fight", "99", 0));
        edit_ap->setText(QApplication::translate("fight_fight", "50", 0));
        label_6->setText(QApplication::translate("fight_fight", "\346\224\273\345\207\273", 0));
        label_7->setText(QApplication::translate("fight_fight", "\351\255\224\346\263\225", 0));
        label_8->setText(QApplication::translate("fight_fight", "\351\201\223\346\234\257", 0));
        label_9->setText(QApplication::translate("fight_fight", "\345\233\236\350\241\200", 0));
        label_10->setText(QApplication::translate("fight_fight", "\351\255\224\351\230\262", 0));
        label_11->setText(QApplication::translate("fight_fight", "\347\211\251\351\230\262", 0));
        label_12->setText(QApplication::translate("fight_fight", "\346\232\264\345\207\273\344\274\244\345\256\263", 0));
        label_13->setText(QApplication::translate("fight_fight", "\345\233\236\346\260\224", 0));
        label_14->setText(QApplication::translate("fight_fight", "\345\233\236\350\223\235", 0));
        label_15->setText(QApplication::translate("fight_fight", "\346\232\264\345\207\273\346\246\202\347\216\207", 0));
        label_16->setText(QApplication::translate("fight_fight", "\346\227\240\350\247\206\351\230\262\345\276\241", 0));
        label_17->setText(QApplication::translate("fight_fight", "\346\224\273\345\207\273\351\200\237\345\272\246", 0));
        edit_role_penetrate->setText(QApplication::translate("fight_fight", "0", 0));
        label_18->setText(QApplication::translate("fight_fight", "\345\233\236\346\260\224", 0));
        label_19->setText(QApplication::translate("fight_fight", "\346\227\240\350\247\206\351\230\262\345\276\241", 0));
        label_20->setText(QApplication::translate("fight_fight", "\346\224\273\345\207\273", 0));
        label_21->setText(QApplication::translate("fight_fight", "\351\255\224\351\230\262", 0));
        label_22->setText(QApplication::translate("fight_fight", "\351\201\223\346\234\257", 0));
        label_23->setText(QApplication::translate("fight_fight", "\347\211\251\351\230\262", 0));
        label_24->setText(QApplication::translate("fight_fight", "\346\232\264\345\207\273\344\274\244\345\256\263", 0));
        label_25->setText(QApplication::translate("fight_fight", "\345\233\236\350\223\235", 0));
        label_26->setText(QApplication::translate("fight_fight", "\351\255\224\346\263\225", 0));
        label_27->setText(QApplication::translate("fight_fight", "\346\224\273\345\207\273\351\200\237\345\272\246", 0));
        label_28->setText(QApplication::translate("fight_fight", "\346\232\264\345\207\273\346\246\202\347\216\207", 0));
        label_29->setText(QApplication::translate("fight_fight", "\345\233\236\350\241\200", 0));
        label_30->setText(QApplication::translate("fight_fight", "\346\200\222\346\260\224", 0));
        label_31->setText(QApplication::translate("fight_fight", "\351\255\224\346\263\225", 0));
        label_32->setText(QApplication::translate("fight_fight", "\344\275\223\345\212\233", 0));
        progressBar_role_hp->setFormat(QApplication::translate("fight_fight", "%v", 0));
        progressBar_role_mp->setFormat(QApplication::translate("fight_fight", "%v", 0));
        progressBar_role_ap->setFormat(QApplication::translate("fight_fight", "%v", 0));
        progressBar_monster_ap->setFormat(QApplication::translate("fight_fight", "%v", 0));
        progressBar_monster_hp->setFormat(QApplication::translate("fight_fight", "%v", 0));
        progressBar_monster_mp->setFormat(QApplication::translate("fight_fight", "%v", 0));
        groupBox->setTitle(QApplication::translate("fight_fight", "\347\212\266\346\200\201", 0));
        checkBox_MultipleReputation->setText(QApplication::translate("fight_fight", "\345\217\214\345\200\215\345\243\260\346\234\233\345\211\251\344\275\231", 0));
        checkBox_MultipleDrop->setText(QApplication::translate("fight_fight", "\345\217\214\345\200\215\346\232\264\347\216\207\345\211\251\344\275\231", 0));
        checkBox_MultipleExp->setText(QApplication::translate("fight_fight", "\345\217\214\345\200\215\347\273\217\351\252\214\345\211\251\344\275\231", 0));
        label_33->setText(QApplication::translate("fight_fight", "LT", 0));
        label_34->setText(QApplication::translate("fight_fight", "RT", 0));
        label_35->setText(QApplication::translate("fight_fight", "%", 0));
        label_36->setText(QApplication::translate("fight_fight", "%", 0));
        label_37->setText(QApplication::translate("fight_fight", "%", 0));
    } // retranslateUi

};

namespace Ui {
    class fight_fight: public Ui_fight_fight {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FIGHT_FIGHT_H
